### PR TITLE
Prevent toggling spell-check when there is no active text editor

### LINKED ISSUE #130: Uncaught TypeError: Cannot read property 'id' of undefined
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Microsoft Windows 10 Home
**Thrown From**: [spell-check](https://github.com/atom/spell-check) package, v0.67.0

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At C:\Users\Gouthaman\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\spell-check\lib\main.js:43

TypeError: Cannot read property 'id' of undefined
    at Object.module.exports.toggle (C:\Users\Gouthaman\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\spell-check\lib\main.js:43:54)
    at atom-workspace.commandSubscription.atom.commands.add.spell-check:toggle (C:\Users\Gouthaman\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\spell-check\lib\main.js:13:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Gouthaman\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Gouthaman\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Gouthaman\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\Gouthaman\AppData\Local\atom\app-1.7.2\resources\app.asar\src\atom-environment.js:1100:28)
    at EventEmitter.outerCallback (C:\Users\Gouthaman\AppData\Local\atom\app-1.7.2\resources\app.asar\src\application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -1:18.1.0 application:add-project-folder (ul.list-inline.tab-bar.inset-panel)
     -0:52.3.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -0:49.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:45.3.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -0:42 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:22.9.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -0:19.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:18.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:14.2.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -0:05.7.0 spell-check:toggle (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "angularjs-styleguide-snippets-es6"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs-styleguide-snippets, v0.7.3

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by roccosportal**
Fixes #130

### CODE REVIEW

File: lib/main.coffee [hunk 1]
```diff
@@ -27,6 +27,8 @@ module.exports =
 
   # Internal: Toggles the spell-check activation state.
   toggle: ->
+    if not atom.workspace.getActiveTextEditor()
```
Comment (50Wliu) [inline lib/main.coffee]: This can be condensed into `return unless atom.workspace.getActiveTextEditor()`

**Comment by as-cii** [comment]
Thanks @roccosportal!
